### ISSUE TITLE
Blackmagic Videohub 16x32 Route problems

### ISSUE THREAD

**Issue by cschaftenaar** [bitfocus/companion-module-videohub#3]
Hi programmer(s) (William Viker)

I think i have a bug found in the Blackmagic Videohub module.
Blackmagic Videohub 16x32 (old HD version) has 16 inputs and 32 outputs.
I can only route to 16 outputs instead of 32. I can't route any input to the 16 other outputs (Labeled as 'Monitor') Is it possible to fix it?
Below are the pics of the Videohub.

Thanx in advance!
Greatings Christiaan Schaftenaar

![studio-videohub_01](https://user-images.githubusercontent.com/21192996/54595601-46048680-4a33-11e9-931e-4560198b7427.png)
![S_873224-MLB25658840391_062017-O](https://user-images.githubusercontent.com/21192996/54595620-4e5cc180-4a33-11e9-9b2f-56d6aa620e0a.jpg)

**Comment by cschaftenaar** [comment]
Is this bug fixed @krocheck ?

**Comment by krocheck** [comment]
Go ahead and give the latest build a try (1359 or higher).  I think its fixed but I had no way of testing.

Also, if you're able to rest the RS422 routing I would appreciate it.

**Comment by cschaftenaar** [comment]
Super! :-) I'll give it a try as soon as iám home from work. I'll let you know if it works @krocheck .
Iám sorry but i can't test the RS422 because i don't use it. :-(

**Comment by cschaftenaar** [comment]
O where can i download the latest build @krocheck ?

**Comment by krocheck** [comment]
https://builds.bitfocus.io/companion/

**Comment by cschaftenaar** [comment]
Hi @krocheck everything seems to work! Great work! Thanx 😊 o I think that I can test the routing of the RS422. tomorrow I am going do some test. I'll let you know if it works.

**Comment by krocheck** [comment]
No prob.  Thanks!

**Comment by cschaftenaar** [comment]
Hi krocheck,

Sorry for the late answer. The RS422 is working fine. The only thing what missing in the pull-down is the option - Disconnected. You can Disconnected a port in the original BMD program.
This option is also available in the pull-down.

**Comment by cschaftenaar** [comment]
The disconnect option makes the source and destinations the same

**Comment by krocheck** [comment]
Interesting.  If you route, as an example, source 2 to source 2 is that the same as what the software shows as disconnected?  It might be difficult to achieve that same structure in our dropdowns.

**Comment by cschaftenaar** [comment]
That's true. I have made a picture of an example. See source 6.

![IMG_20190404_215308](https://user-images.githubusercontent.com/21192996/55584319-38821880-5724-11e9-9796-54ae7c97d1f1.jpg)

**Comment by krocheck** [comment]
Yeah, so long as the ultimate behavior is the same, the user would need to know to route to port to itself to achieve that result.  We'd have to dynamically re-draw the source dropdown based on the selected destination.  Way more work than its worth.

**Comment by cschaftenaar** [comment]
The behavior is the same if you route to port to itself. I't is not a problem for me to keep it as it is now.
But i wanted to let you know. :-)

Thanxs for the very good support  :-)

**Comment by krocheck** [comment]
Copy that.  Thanks, and no prob!
