### ISSUE TITLE
Videohub Preset Instances being reset when Companion is restarted

### ISSUE THREAD

**Issue by theColourSpace** [bitfocus/companion-module-videohub#6]
I don't know if this applies only to videohub instances or others, but the button instance setting is getting erased between restarts of companion. 

I have dragged over the presets for my sources, assigned them to buttons for both destination and source. The instance indication for this works spectacularly. 

But if I restart the companion (running headless on a pi) it will retain the source and destination routing aspects of the button settings but reset the instance config. So that I need to reconfigure the instance after every restart.

Running 1.3.0 (596e7f6-1412).

**Comment by krocheck** [comment]
@theColourSpace did we ever determine that this is no longer an issue in the recent v2.0 builds?

**Comment by theColourSpace** [comment]
> @theColourSpace did we ever determine that this is no longer an issue in the recent v2.0 builds?

Indeed, works a charm now!

**Comment by krocheck** [comment]
Thanks!
